### ISSUE TITLE
Regex bump handling

### ISSUE THREAD

**Issue by annymsMthd** [syncromatics/gogitver#5]
I would like to add a settings yaml to keep things like the regexes used for version bumps. Maybe something like:

```yaml
bump:
  major:
    - "\\(\\+semver: major\\)"
    - "\\(\\+semver: breaking\\)"
  minor:
    - "\\(\\+semver: feature\\)"
    - "\\(\\+semver: minor\\)"
  patch:
   - "(\\(\\+semver: patch\\)"
   - "\\(\\+semver: fix\\)"
```
